name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: "-Xmx4g"
      ORG_GRADLE_JVMARGS: "-Xmx4g"

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Cache Kotlin compiler
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            ~/.kotlin
          key: kotlin-compiler-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: kotlin-compiler-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run lint checks
        run: ./gradlew lintDebug --no-daemon --stacktrace

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace

      - name: Build debug APK
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
